version: '3'
services:
  server:
    image: 'nginx:alpine'
    links: 
      - 'php'
    ports: 
      - '8080:80'
    volumes: 
      - './nginx.conf:/etc/nginx/conf.d/default.conf'
      - './htdocs/:/var/www/html/'
      - './symlinked-folder:/var/www/html/symlinked-folder'
    # privileged: true
  php:
    image: 'php:7.1-fpm-alpine'
    volumes: 
      - './htdocs/:/var/www/html/'
      - './symlinked-folder:/var/www/html/symlinked-folder'

